version: '2'
services:
  # To init base configuration run:
  # docker exec -ti  infrastructurem_inspector_1 bash
  # ./scripts/dominant/commit-base-fixture.sh -v

#  walker:
#      image: walker:local
#      entrypoint: ""
#      command: [ "java", "-Xmx512m", "-jar", "/opt/walker/walker.jar"]

  inspector:
    image: dr.rbkmoney.com/rbkmoney/holmes:e1e866ad74f517c3370f167b6c7a6b7c948c53c6

  hellgate:
    image: dr.rbkmoney.com/rbkmoney/hellgate:bcd776a4185747f22ae5b260dd1e8774b0607d57
    command: [ "/opt/hellgate/bin/hellgate",  "foreground"]
    ports:
      - "8022:8022"
    volumes:
      - ./hellgate/sys.config:/opt/hellgate/releases/1/sys.config
    depends_on:
      - machinegun
      - dominant

  machinegun:
    image: dr.rbkmoney.com/rbkmoney/machinegun:bde2440a87e8311b6e2db90e915f8efdaa520ba1
    command: /opt/machinegun/bin/machinegun foreground
    volumes:
      - ./machinegun/sys.config:/opt/machinegun/releases/0.1.0/sys.config

  dominant:
    image: dr.rbkmoney.com/rbkmoney/dominant:9c757f3fdeae26423b777901da528cdd675dfa40
    command: /opt/dominant/bin/dominant foreground
    depends_on:
      - machinegun

  bustermaze:
    image: dr.rbkmoney.com/rbkmoney/bustermaze:57c4cf3f9950b6ee46f67ffca286ebe8267bedde
    container_name: bustermaze
    entrypoint:
      - java
    command: -Xmx512m
        -Dhg.pooling.url=http://hellgate:8022/v1/processing/eventsink
        -jar /opt/bustermaze/bustermaze.jar
        --spring.datasource.url=jdbc:postgresql://bustermaze-db:5432/bustermaze
        --spring.datasource.username=postgres
        --spring.datasource.password=postgres
        --flyway.url=jdbc:postgresql://bustermaze-db:5432/bustermaze
        --flyway.user=postgres
        --flyway.password=postgres
        --flyway.schemas=bm
    ports:
      - "8023:8022"
    depends_on:
      - hellgate
      - bustermaze-db

  bustermaze-db:
    image: dr.rbkmoney.com/rbkmoney/postgres:9.6
    environment:
      - POSTGRES_DB=bustermaze
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SERVICE_NAME=bustermaze-db


  shumway:
    image: dr.rbkmoney.com/rbkmoney/shumway:cd00af9d70b28a7851295fca39bdeded5a3606b0
    entrypoint:
      - java
    command:
      -Xmx512m
      -jar /opt/shumway/shumway.jar
      --spring.datasource.url=jdbc:postgresql://shumway-db:5432/shumway
      --spring.datasource.username=postgres
      --spring.datasource.password=postgres
    depends_on:
      - shumway-db

  shumway-db:
    image: dr.rbkmoney.com/rbkmoney/postgres:9.6
    environment:
      - POSTGRES_DB=shumway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SERVICE_NAME=shumway-db

      # Better start Jira in separate container with start_jira.sh script
  jira:
    image: dr.rbkmoney.com/rbkmoney/walker/test-jira:0.1
    command: ['atlas-run-standalone', '--product',  'jira' , '-Dallow.google.tracking=false']
    tty: true
    ports:
      - "2990:2990"


networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"
