version: '2'
services:
  hellgate:
    image: dr.rbkmoney.com/rbkmoney/hellgate:ee85cc90d487c2d7d870a6912171da4bbc41af4d
    volumes:
      - .:/Users/alexeysemenkov/git/hellgate
      - /Users/alexeysemenkov/.cache:/home/alexeysemenkov/.cache
    working_dir: /Users/alexeysemenkov/git/hellgate
    ports:
      - "8022:8022"
    depends_on:
      - machinegun
  machinegun:
    image: dr.rbkmoney.com/rbkmoney/machinegun:cc5985c4b1ea385eba141995c37ebc67093a1fe7
    volumes:
      - ./test/machinegun/sys.config:/opt/machinegun/releases/0.1.0/sys.config

#  bustermaze:
#     image: dr.rbkmoney.com/rbkmoney/bustermaze:3ad50e51cbc0982d98c593433d12fbc83ccfded0
#     volumes:
#       - .:/code
#       - /Users/alexeysemenkov/.m2:/tmp/m2_settings_xml
#     working_dir: /code
#     depends_on:
#       - bm_db
#
#  bm_db:
#    image: postgres:9.6
#    container_name: bm_postgres
#    ports:
#      - "5432:5432"
#    environment:
#         POSTGRES_PASSWORD: postgres
#         POSTGRES_USER: postgres
#         POSTGRES_DB: bustermaze

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"
